### ISSUE TITLE
[Feature Request] Add SpamWatch integration

### ISSUE THREAD

**Issue by ajhalili2006** [SpEcHiDe/UniBorg#61]
I would suggest adding integration with SpamWatch so user bots can also banhammer spammers on SpamWatch.

## TO-DO for Maintainers
If you agree with my suggestion, please follow this to-do. Anyone can use this to-do to craft their own Merge Requests containing the SpamWatch integration.
* [x] Add `spamwatch` to the `requirements.txt`.
* [x] Pull `plugins/autobahn` files from [Kantek](https://github.com/mojurasu/kantek).
* [x] Add `SPAMWATCH_API_TOKEN` and `SPAMWATCH_API_HOST` (for self-hosted SpamWatch API servers) to configuration.
 * If those config keys are undefined, disable Kantek plugins.
 * If the `SPAMWATCH_API_HOST` config key is undefined, automatically point API requests to `https://api.spamwat.ch`
* [ ] Run CI dry-runs and manual testing to confirm its works.

## Notes
* From Kantek's README:
> Kantek is mostly built to help with the Administration of chats and is the main source for SpamWat.ch. Because of that it checks every message your account receives for blacklisted items, this includes strings, domains, top level domains, files, images and telegram entities. This means that for every message your account receiver kantek might make multiple http requests an resolve multiple telegram entities. The latter might lead to large (6+ hours) Floodwaits from Telegram.

**Comment by muhammedfurkan** [comment]
this plugin already have it in my repo. [Check this out ](https://github.com/muhammedfurkan/UniBorg/blob/master/stdplugins/spamwatch.py)

**Comment by ajhalili2006** [comment]
> this plugin already has it in my repo. [Check this out ](https://github.com/muhammedfurkan/UniBorg/blob/master/stdplugins/spamwatch.py)

Do you make a PR about that? To make it officially available in the repo, it should be merged. @muhammedfurkan

**Comment by muhammedfurkan** [comment]
> > this plugin already has it in my repo. [Check this out ](https://github.com/muhammedfurkan/UniBorg/blob/master/stdplugins/spamwatch.py)
> 
> Do you make a PR about that? To make it officially available in the repo, it should be merged. @muhammedfurkan

okay, check #63

**Comment by muhammedfurkan** [comment]
please canyou close this issue ?

**Comment by ajhalili2006** [comment]
Any update about this?
